function fun(){
    try{
        console.log("Hello sir.");
    }
    catch(err) {
        for(let i=i ; i<3; i++){
            console.log('mini');
        }
    }
    finally{
        console.log('thank you sir')
    }    

}

fun();


// try {
//     const x = 10;
//     if(x===10) throw  error;
// }
// catch {
//     console.log('error');
// }